### ISSUE TITLE
Cannot access mysql

### ISSUE THREAD

**Issue by anonymous-careful-reviewer** [caseqiu213/reqracer_fse_artifact#4]
Looking in INSTALL, I cannot figure out how to log into mysql. (I have not done this in awhile).

I run the command from the INSTALL:

```
anonymous@anonymous-VirtualBox:~/Desktop/reqracer_fse_artifact$ /usr/local/mysql/bin/mysql -u root -p.
Warning: Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by caseqiu213** [comment]
Make sure /tmp/reqracer is created. If not, you may need to manually run in reqracer_fse_artifact directory
`sudo ./prepare_log_files.sh`.

The problem seems to be that the script did not set up the password correctly. Alternatively, as mentioned in the comment in our script, you can 
`cd /usr/local/mysql`
`sudo ./bin/mysql_secure_installation`
The default root password is empty, so you can hit enter and follow the pop-up to proceed.
The password set by our script is `reqracer-mysql`, so please use it as the new password.
After the setup, you can log in MySQL using `sudo ./bin/mysql -u root -p` and enter the password you just set.

**Comment by anonymous-careful-reviewer** [comment]
I'm not sure if we can close this issue yet. Do you understand what went wrong with the 

```
Alternatively, as mentioned in the comment in our script
```

Hmm, if you want people to be able to read your script, perhaps you can introduce some `echo Now doing xyz` statements, and redirect the log output to a file in `/tmp/reqracer-install-$YYMMDD`? Then it would be easy to read the stdout of the install script, and know where to look. At the moment the output is extremely verbose, so I could not easily find the point where the script is doing something strange.

(This change could be accompanied running a `set -x; set -e` at the top of the script, so that failures are caught earlier)

**Comment by anonymous-careful-reviewer** [comment]
```
Make sure /tmp/reqracer is created. If not, you may need to manually run in reqracer_fse_artifact directory
```

It was not created. I have manually run the command you said. (Note that this failure is problematic -- This is a clean Ubuntu 18.04 VM, so your steps should work...Have you tried your steps in a clean Ubuntu install?)

**Comment by caseqiu213** [comment]
I just verified on a fresh Ubuntu install. The solution is to run `prepare_log_files.sh` before `build.sh`, and README is updated.
