### ISSUE TITLE
Cannot follow steps to Install Application

### ISSUE THREAD

**Issue by anonymous-careful-reviewer** [caseqiu213/reqracer_fse_artifact#8]
I am on [installing application](https://github.com/caseqiu213/reqracer_fse_artifact#installing-application).

It says to go to PHP and create a database with a name I prefer, or with a bug name (where does such a bug name come from?). I chose the name "test". I also tried the number name "11073" since that seems to be a bug name.

I decide to try a WordPress bug. It says:

```
WordPress(11073, 11437, 24933)

    Edit htdocs/bug_number/wp-config-sample.php, enter DB_NAME(the database name), DB_USER(your mysql account name), DB_PASSWOR(your mysql password), and save as wp-config.php.
    In the brwoser, type in localhost:8080/bug_number/index.php, and follow the pop-up instructions to finish setting up the application.
```

I suppose by `htdocs` you mean `build/apache/htdocs`. But there is no subdirectory named "bug_number", nor is there a directory named anything other than `phpMyAdmin` in the `htdocs` directory.

Am I supposed to create the subdirectory `htdocs/<DB NAME>` myself? The README is unclear. I am not sure what to do next. It would also be helpful to know if there is a strict requirement to use a name from one of the bugs, or if that is just a mnemonic recommendation.

(A worked example for the first WordPress bug would be helpful, with explicit data to use in each step.)

**Comment by caseqiu213** [comment]
The bug code are located at `reqracer_fse_artifact/bug_code`. You need to copy all folders in it to `reqracer_fse_artifact/build/apache/htdocs`.
We provide a database snapshot for bug 11073 so that you can follow the steps in our demo video. If you created a new database, you can run `/usr/local/mysql/bin/mysql < ./reqracer_fse_artifact/wordpress_db.sql` to restore the snapshot. The admin credentials for bug 11073 are: username: caseqiu, password: 1qazxsw2.
